---
title: "EKT 813: Quants"
subtitle: "Project 2"
author: "Prof SF Koch"
date: "today"
format: 
  html:
    theme: cosmo
    toc: true
editor: visual
bibliography: 
  - project-refs-v1.bib
  - data-v1.bib
---

**Not final version, yet!**

\*Due date: April 30, 17:00.\^\[May 1 is a public holiday, so I think it best to complete it before the holiday.\] Please, email the project to me. The project submission should contain a 'README' file that describes the exact steps needed to get to the data and results that you are using for the analysis: where to get the data, which files, which 'program' files to run in which order to get all the data and all of the results. All program files should have comments describing the steps being undertaken, explaining variable definitions and so on. The project submission should also contain a 'Report' file that presents the information requested in the project in the format requested.

You are allowed/encouraged to work in groups of three, preferably the same three. If your group is short, please, contact me, immediately. Each group should continue with their wave of data - there are five. Thus, multiple groups will work on the same wave of data.

As I have noted, I will not force you to use any specific software.

# Introduction

(Repeated from Project I) Research into health demand in South Africa is limited, primarily because there is minimal publicly available health related data. Given the desire to implement an NHI, however, it is necessary to develop a larger evidence base on the demand for health care and begin to consider what an NHI might do to the demand for services. Over this semester, we are going to begin to develop some descriptive and regression evidence related to the demand for health care.

South African research has highlighted inequalities in access to health care [@Gordonetal2020; @MhlangaGaridzirai2020], costs and benefits of health care services and financing [@atagubamcintyre2012], use of health care and/or medical aid access [@omotosokoch2017] and out-of-pocket payments [@KochSetshegetso2021]. Some of those inequalities have declined over the last few decades [@DayZondi2019]. Related research has highlighted quality problems [@Hondaetal2015] and poor public perception associated with the public sector [@BurgerChristian2020]. Much of that research has also argued for the furtherance of universal health care [@ataguba2016], primarily through a national health insurance scheme. Currently, most care received in the private sector is for those with access to medical aids -- as health insurance is called in the country -- although private healthcare is purchased by those without medical aids [@StatsSA_MbaloBrief2023]. However, research on the private sector has suggested that its care is very expensive, at least relative to income levels [@LorenzoniRoubal2016], may not generate the health outcomes expected [@KochSlabbert2012] and suffers from supplier-induced demand, although there is no empirical evidence of it [@ErasmusKean2018].

# Data

(Repeated from Project I) Unfortunately, data on illness in South Africa is generally limited to being diagnosed with a chronic condition, although there are also measures of limitations in activities of daily living, as well as self-assessed health. Some of the surveys include questions related to where consultations would normally take place in the event someone fell ill.

The survey with the most extensive health information is the National Income Dynamics Study [@nids_wave1_2008; @nids_wave2_2010; @nids_wave3_2012; @nids_wave4_2014; @nids_wave5_2017]. All five waves contain rather similar questions related to health; of particular interest for this research are questions related to whether someone has been ill in the last 30 days, and, if so, what was done to treat it. An unfortunate problem with the NIDS data is that it does not capture income or expenditure as well as one would like, although they impute missing income, which helps some.

In terms of the data that will be used for the analysis, we will capture all (adult-focused)[^1] health and healthcare seeking information (including illness, behaviours, medical aid coverage and/or medical expenses), as well as standard socio-demographic controls, such as: income/expenditure, education, age, population group, gender. Yes, there is likely to be more information that is useful. For our purposes, however, this is enough.

[^1]: NIDS has a separate child survey that would be interesting to examine, but will not be the focus of this research, given the time and other resources available.

# Project II

Our plan is to continue moving forward with the previous work. However, now that you have managed to gain some understanding with the 'adult' file from your wave. I would like you to access other files from the same wave, if needed to 'fix' any of the variables from the previous project. In particular, please, try to capture household level income and expenditure; often, this information is imputed by NIDS. Please, loosely outline what was done in the imputation within the report.

## Data development

For this project, I would like your groups to make use of the household expenditure and income data, as well as the health and demographic data from the last project - although some of that data should be updated from other files in the Wave, if needed.

Your final dataset should not have all that many additional variables, when compared to the previous project.

## Data presentation

I would like to see a data description table, which might be a slight modification and extension to the previous one. In addition, I would like to see whether there is any difference in the density and/or distribution\^\[I am not expecting anyone to use the np package, as I showed in the one set of notes; it is possible to illustrate densities with `geom_density`, for example, and distributions with the `ecdf` function.\] of income/expenditure by medical aid status of the household head, as well as the self-assessed health status of the household head (if not self-assessed health). This can be done at the mean and the distribution.. Finally, I would like to see a concentration curve for self-assessed health status of the household head (that is ranked by income)

## Report

Your report should describe what you did to get to the table and figure(s); however, keep in mind that the README is an exact statement of how. Thus, we are after an overview and highlights of the process. The report should also offer a useful summary of the table; again, the table is 'exact', so we do not want it repeated in the text. Instead, we want an overview and highlights.[^2] I would like to see some interpretation of the illustrations. Again, I do not want to see an exact description. Rather, I want an overview and highlights and any summary of statistical tests used to ascertain comparisons.

[^2]: To get examples of this, feel free to read papers making use of this or any other data, or even technical documents about the data.

Be sure to site the data, and any software and user developed packages that were used to get there. Please, feel free to present the report as an html file and the readme as most anything (although markdown, html or text is probably the easiest). Given that you do not really need to worry about whether illustrations or tables fit nicely - admittedly, I would rather not see figures and tables that are overly wide requiring me to scroll all over back and forth.

Finally, it is impossible to give a page/word limit, but I would think a few paragraphs to outline what you did to get the data together, another few to get the table together another few to get the figures together and a final few to describe each set of 'results'; this might be more than last time as there is an implication that a statistical test or two are to be included, as well as specific types of curves. Thus, some methods should be part of the report.

# References
